spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8090
              predicates:
                - Path=/internal/auth/**, /api/v1/auth/**
            - id: user-service
              uri: http://localhost:8070
              predicates:
                - Path=/internal/users/**, /api/v1/users/**
            - id: course-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/courses/**

eureka:
  client:
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8222