spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/auth/**

eureka:
  client:
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8222