spring:
  application:
    name: progress-service
  data:
    redis:
      host: localhost
      port: 6380
      database: 0
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: progress_db
      authentication-database: admin
  kafka:
    bootstrap-servers: 172.19.94.160:9092
    consumer:
      group-id: progress-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            type:
              mapping: 'studentEnrolledEvent:com.dev.quikkkk.progress_service.dto.kafka.StudentEnrolledEvent'

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8020