spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6380
      database: 0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_schema: public

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  config:
    auth-service-url: http://localhost:8222/internal/auth
  security:
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      tags-sorter: alpha
      operations-sorter: alpha
      display-request-duration: true
    show-actuator: true
    default-produces-media-type: application/json
    default-consumes-media-type: application/json

server:
  port: 8070
